config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  
  controller :pages do
    get :index
    get :pacientes
    get :colegas
    get :tudoctor
    get :contacto
  end


  get '_ah/health', to: 'appengine#health'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def colegas
  end
  def pacientes
  end
  def tudoctor
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<br>
<br>
<br>
<br>
<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <br>
      <span class="text-muted">
        <p>
          &nbsp;<a href="/">
          <i class="fa fa-linkedin-square" aria-hidden="true"></i> Dr. Nicolas Troncoso
          </a>
        </p>
      </span>
      <span class="text-muted">
        <p>
          &nbsp;&nbsp;<a href="mailto:doctor@nicolastroncoso.cl" target="_top"><i class="fa fa-envelope-o" aria-hidden="true"></i> doctor@nicolastroncoso.cl</a>
        </p>
      </span>
    </div>
</nav>

app/views/layouts/_navigation.html.erb
  <header class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header navbar-default navbar-nav">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to index_path do %>
              <%= content_tag :span, "Dr. Nicolas Troncoso", :class => "navbar-brand" %>
            <% end %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <li>
                  <%= link_to 'Pacientes', pacientes_path %>
                </li>
                <li>
                    <%= link_to 'Tu Doctor', tudoctor_path %>
                </li>
                <li>
                    <%= link_to 'Contacto', contacto_path %>
                </li>
                <li>
                  <%= link_to 'Colegas', colegas_path %>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nicolas Troncoso</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Shadows+Into+Light" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sitio Web de Doctor Nicolas Troncoso">
    <meta name="author" content="Jorge Romussi">
    <meta name="google-site-verification" content="btFLvoIRFnsHGJXrVqfdwIKm2Dc60Bk0HhshZJW7h-g" />

  </head>

  <body>
    <!-- Navigation -->
    <%= render'layouts/navigation' %>
    <%= yield %>
    <%= render'layouts/footer' %>
  </body>
</html>

app/views/pages/colegas.html.erb
<!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
          <div class="col-md-12 text-center vision"><h3>"implementacion, no entiendo la letraaa."</h3></div>
            <div class="col-lg-12">
                <h1 class="page-header center">Colegas
                </h1>
            </div>
        </div>
        <!-- /.row -->
        <div class="container">
          <div class="borderless">
            <div class="row">
              <ul class="list-group">
                <span style="cursor:pointer"><h3>
                  <li class="list-group-item borderless"  data-toggle="collapse" data-target="#colega1">
                    <i class="fa fa-arrow-right" aria-hidden="true"></i> Endoscopia</li></h3>
                </span>
                <div id="colega1" class="collapse">
                  <li class="list-group-item borderless">
                    <div class="row">
                      <div class="col-md-2">
                        <img class="img-responsive" src="http://placehold.it/200x200" alt="">
                      </div>
                      <div class="col-md-9">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      </div>
                    </div>
                  </li>
                </div>
                <span style="cursor:pointer"><h3>
                  <li class="list-group-item borderless"  data-toggle="collapse" data-target="#colega2">
                  <i class="fa fa-arrow-right" aria-hidden="true"></i> Cirugia</li></span></h3>
                <div id="colega2" class="collapse">
                  <li class="list-group-item borderless">
                    <div class="row">
                      <div class="col-md-2">
                        <img class="img-responsive" src="http://placehold.it/200x200" alt="">
                      </div>
                      <div class="col-md-9">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      </div>
                    </div>
                  </li>
                </div>
                <span style="cursor:pointer"><h3>
                  <li class="list-group-item borderless"  data-toggle="collapse" data-target="#colega3">
                  <i class="fa fa-arrow-right" aria-hidden="true"></i> Otra wea</li></span></h3>
                <div id="colega3" class="collapse">
                  <li class="list-group-item borderless">
                    <div class="row">
                      <div class="col-md-2">
                        <img class="img-responsive" src="http://placehold.it/200x200" alt="">
                      </div>
                      <div class="col-md-9">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      </div>
                    </div>
                  </li>
                </div>

              </ul>
            </div>
          </div>
      </div>

        <!-- /.row -->
    </div>
<!-- /.row -->

app/views/pages/contacto.html.erb
<!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header center">Nicolas Troncoso
                </h1>
            </div>
        </div>
        <!-- /.row -->
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <span class="text-muted">
                <p>
                  <h4><a href="mailto:doctor@nicolastroncoso.cl" target="_top"><i class="fa fa-envelope-o" aria-hidden="true"></i> doctor@nicolastroncoso.cl</a></h4>
                </p>
                <p>
                  <h4><a href="tel:0056912345678"><i class="fa fa-phone" aria-hidden="true"></i> +56912345678</a></h4>
                </p>
                <p>
                  <h4><a href="whatsapp://send?phone=+56912345678"><i class="fa fa-whatsapp" aria-hidden="true"></i> Escribeme por WhatsApp</a></h4>
                </p>
              </span>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              Contactame, solucionare tus dudas.
            </div>
          </div>
        </div>
        <!-- /.row -->
    </div>
<!-- /.row -->

app/views/pages/index.html.erb
  <!-- Page Content -->



                  <div class="header"></div>
                        


            <!-- /.container -->
        <!-- /.row -->
  <br>

    <!-- /.container -->

app/views/pages/pacientes.html.erb
<!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
          <div class="col-md-12 text-center vision"><h3>"Mi vision es ser el mejor dostor."</h3></div>
            <div class="col-lg-12">
                <h1 class="page-header center">Pacientes
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
          <div class="col-md-4">
          </div>
          <div class="col-md-4">
          </div>
          <div class="col-md-4">
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
            <h3>Odontologia 1</h3>
            <br><br>
            <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            <br>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
          </div>
          <div class="col-md-6">
            <h3>Odontologia 2</h3>
            <br><br>
            <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            <br>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
          </div>
        </div>
        <br>
        <hr>
        <br>

        <!-- /.row -->
    </div>
<!-- /.row -->

app/views/pages/tudoctor.html.erb
<!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header center">Nicolas Troncoso
                </h1>
            </div>
        </div>
        <!-- /.row -->
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
              quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
              <ul class="list-group-item borderless">
                <li class="list-group-item borderless"><small><i class="fa fa-circle" aria-hidden="true"></i></small> titulado</li>
                <li class="list-group-item borderless"><small><i class="fa fa-circle" aria-hidden="true"></i></small> 4to medio</li>
                <li class="list-group-item borderless"><small><i class="fa fa-circle" aria-hidden="true"></i></small> dostor</li>
                <li class="list-group-item borderless"><small><i class="fa fa-circle" aria-hidden="true"></i></small> deporte</li>
              </ul>
            </div>
          </div>
        </div>
        <br>
        <div class="container">
          <div class="row">
            <p>
            <div class="col-md-4">
              <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </div>
            <p>
            <div class="col-md-4">
              <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </div>
            <p>
            <div class="col-md-4">
              <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </div>
          </div>
          <br>
          <div class="row">
            <p>
            <div class="col-md-4">
              <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </div>
            <p>
            <div class="col-md-4">
              <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </div>
            <p>
            <div class="col-md-4">
              <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </div>
          </div>
        </div>
        <br>

        <!-- /.row -->
    </div>
<!-- /.row -->